name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  stack:
    name: stack - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

      - uses: actions/setup-haskell@v1.1
        name: Setup Haskell Stack
        with:
          enable-stack: true
          stack-version: latest

      - uses: actions/cache@v2
        name: Cache ~/.stack
        with:
          path: |
            C:\sr
            ~\AppData\Local\Programs\stack
            ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - name: Build
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: |
          stack test --system-ghc
